# Generated by Django 5.0.6 on 2024-08-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('tracker', '0002_organization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
