# Generated by Django 5.0.6 on 2024-07-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
