# Generated by Django 5.0.6 on 2024-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_useraccount_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('employee', 'Employee'), ('freelancer', 'Freelancer')], default='freelancer', max_length=20),
        ),
    ]
