# Generated by Django 5.0.6 on 2024-07-11 04:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('US', 'USD'), ('PK', 'PKR'), ('EU', 'EUR'), ('GB', 'GBP'), ('JP', 'JPY'), ('CA', 'CAD'), ('AU', 'AUD'), ('IN', 'INR'), ('CN', 'CNY'), ('SG', 'SGD'), ('CH', 'CHF'), ('NZ', 'NZD'), ('RU', 'RUB'), ('BR', 'BRL'), ('ZA', 'ZAR')], default='US', max_length=3)),
                ('allow_web_tracker', models.BooleanField(default=True)),
                ('allow_desktop_tracker', models.BooleanField(default=True)),
                ('take_screenshots', models.BooleanField(default=True)),
                ('screenshot_interval', models.PositiveIntegerField(default=30)),
                ('mouse', models.BooleanField(default=True)),
                ('keyboard', models.BooleanField(default=True)),
                ('manual_time', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='authentication.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('S', 'Supervisor'), ('W', 'Worker')], default='W', max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_engagements', to='authentication.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='tracker.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('S', 'Supervisor'), ('W', 'Worker')], default='W', max_length=1)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='authentication.profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='shots')),
                ('type', models.CharField(choices=[('s', 'Screenshot'), ('w', 'Web Cam')], default='s', max_length=1)),
                ('blurred', models.BooleanField(default=False)),
                ('is_time_randomized', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('associated_shot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.shot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('work_from', models.TimeField()),
                ('work_to', models.TimeField()),
                ('type', models.CharField(choices=[('D', 'Desktop'), ('M', 'Manual'), ('W', 'Web'), ('B', 'Mobile')], max_length=1)),
                ('keyboard_event_counts', models.PositiveIntegerField(blank=True, default=0)),
                ('mouse_event_counts', models.PositiveIntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.membership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.project')),
                ('shots', models.ManyToManyField(blank=True, to='tracker.shot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
