# Generated by Django 5.0.6 on 2024-07-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_archived_at'),
        ('tracker', '0003_alter_membership_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('project', 'profile')},
        ),
    ]
