# Generated by Django 5.0.6 on 2024-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_user_membership_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='activity',
            name='work_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='work_to',
            field=models.DateTimeField(),
        ),
    ]
