# Generated by Django 5.0.6 on 2024-07-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_activity_start_date_alter_activity_work_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='member',
        ),
    ]
